### ISSUE TITLE
`vab` doesn't support traget API > 31

### ISSUE THREAD

**Issue by ArtemkaKun** [vlang/vab#261]
When I set up `--api` to 33, `vab` still uses 31 and fails

```
      - name: Setup Android SDK
        uses: amyu/setup-android@v2
        with:
          sdk-version: 33
          build-tools-version: '33.0.2'
          ndk-version: '23.1.7779620'
          cache-disabled: true

      ...

      - name: Build APK
        run: vab --api 33 --archs 'arm64-v8a' -v 3 .
```

```
| Replacing minimum SDK version "21" with "21"
| Replacing target SDK version "21" with "31"
| Replacing declaration of OpenGL ES version "0x00020000" with "0x00020000"
| Replacing activity name "io.v.android.VActivity" with "io.v.android.VActivity"
| Copying assets
| Running aapt From: /home/yuart/Projects/v-project-basement
| /root/.android/sdk/build-tools/33.0.2/aapt package -v -f -m -M "/tmp/vab/package/apk/AndroidManifest.xml" -S "/tmp/vab/package/apk/res" -J "/tmp/vab/package/apk/src" -A "/tmp/vab/package/apk/assets" -I "/root/.android/sdk/platforms/android-31/android.jar"
| Packaging didn't succeed.
| /root/.android/sdk/build-tools/33.0.2/aapt package -v -f -m -M "/tmp/vab/package/apk/AndroidManifest.xml" -S "/tmp/vab/package/apk/res" -J "/tmp/vab/package/apk/src" -A "/tmp/vab/package/apk/assets" -I "/root/.android/sdk/platforms/android-31/android.jar" failed with return code 1:
| asset W 02-26 20:10:16  1238  1238] Asset path /root/.android/sdk/platforms/android-31/android.jar is neither a directory nor file (type=1).
| ERROR: Asset package include '/root/.android/sdk/platforms/android-31/android.jar' not found.
| Found 0 custom asset files in /tmp/vab/package/apk/assets
| Configurations:
|  (default)
|
| Files:
|   mipmap/icon.png
|     Src: () /tmp/vab/package/apk/res/mipmap/icon.png
|   values/strings.xml
|     Src: () /tmp/vab/package/apk/res/values/strings.xml
|   AndroidManifest.xml
|     Src: () /tmp/vab/package/apk/AndroidManifest.xml
|
| Resource Dirs:
|   Type mipmap
|     mipmap/icon.png
|       Src: () /tmp/vab/package/apk/res/mipmap/icon.png
|   Type values
|     values/strings.xml
|       Src: () /tmp/vab/package/apk/res/values/strings.xml
| Including resources from package: /root/.android/sdk/platforms/android-31/android.jar
```
